repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0  # Use the latest stable version
    hooks:
      - id: black

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.287  # Use the latest stable version
    hooks:
      - id: ruff
